#!/bin/bash
# **** License ****
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# This code was originally developed by Vyatta, Inc.
# Copyright (C) 2007-2010 Vyatta, Inc.
# All Rights Reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Description:  Vyatta PAM Radius Authentication Pre-configuration.
#
# **** End License ****

# Disable root login over telnet
sed -i -e '/^# Pseudo-terminal (telnet)/,$d' /etc/securetty
